@URL = https://test-vercel-six-psi.vercel.app

@localURL = http://localhost:3350
POST {{URL}}
Content-Type: application/json

{
    "number": 1300
}

###

POST {{localURL}}
Content-Type: application/json

{
    "number": 1400
}

###

GET {{localURL}}/getYahooFinanceNews