@URL = https://test-vercel-six-psi.vercel.app

@localURL = http://localhost:3350
POST {{URL}}
Content-Type: application/json

{
    "number": 1300
}

###

POST {{localURL}}
Content-Type: application/json

{
    "number": 1400
}

###

GET {{localURL}}/api/v1/news?title=Delta CEO asks CDC to cut quarantine time for breakthrough COVID cases&source=yahoo finance&publishedAt=2021-12-22T04:21:53.964889

###

GET {{URL}}/getYahooFinanceNews
